#!/usr/bin/env bash
#MISE description="Init Terraform modules"
#USAGE flag "--backend" default="false" help="Terraform target to apply. If not specified, all modules will be applied"
#USAGE flag "--upgrade" default="false" help="Automatically approve the apply operation"
#USAGE flag "--migrate-state" default="false" help="Reconfigure a backend, and attempt to migrate any existing state."
#USAGE flag "--reconfigure" default="false" help="Reconfigure a backend, ignoring any saved configuration."

set -ex

TERRAFORM_CLI_ARGS="-upgrade=$usage_upgrade -backend=$usage_backend -migrate-state=$usage_migrate_state -reconfigure=$usage_reconfigure"

terraform init $TERRAFORM_CLI_ARGS
